Fix subset rowdata and allow fast subsetting
hbc/bcbioRnaseq pull request #20
Opened 2017-08-31 18:14 UTC by lpantano

* Including rowData as part to the new object after subsetting
* allow option `skipNorm` to subset without re-calculating normalization for quick plots
* add missing argument in plotDEGHeatmap to know how to change some options

For the second point, I wanted to do a subsetting of `dds` and that's all, but I was facing the same disk space problem. So this integration is the only one I could find working as expecting. The only difference is that the new `dds` object stored doesn't have dispersion. A possible fix is just to plug the dispersion values of the genes after creation. For me was ok, because I just wanted to use `rlog` slot, create a smaller matrix and use some functions to plot the small data. I didn't want to re-normalize or use the `dds`.

2017-08-31 23:56 UTC, mjsteinbaugh approved these changes
Make a couple of suggestions to the NAMESPACE imports in bcbioRnaseq-package.R: DESeqDataSet and DESeqTransform should be imported as classes

2017-09-01 00:34 UTC, mjsteinbaugh requested changes
Using internal `BiocGenerics:::replaceSlots()` doesn't properly pass build checks

2017-09-01 17:00 UTC, lpantano commented
@mjsteinbaugh I fixed that. I don't know why I had that function in biocgenerics, but I changed to standard object creation.

2017-09-01 17:50 UTC, mjsteinbaugh approved these changes

2017-09-01 17:51 UTC, merged