Vbarrera devel
hbc/bcbioRnaseq pull request #42
Opened 2017-10-23 18:57 UTC by vbarrera

A few tweaks to a pair of plots around the interestingGroup options.

2017-10-23 19:37 UTC, lpantano commented on R/methods-plotCorrelationHeatmap.R
> +        interestingGroups= NULL) {
Add interestingGroups to the doc at the beginning of this file. line: 24.

2017-10-23 21:15 UTC, mjsteinbaugh commented
Don't merge this yet – needs to get rebased with master

2017-10-23 21:16 UTC, mjsteinbaugh requested changes
This branch is behind master

2017-10-24 00:19 UTC, vbarrera commented
I'll make the changes over the latest version.

Closing the pull request.

2017-10-24 00:19 UTC, closed without merging